# Generated by Django 3.1.7 on 2021-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='img',
            field=models.ImageField(default=2, upload_to='picture'),
            preserve_default=False,
        ),
    ]
